### ISSUE TITLE
如何在ampart分区后将3.14内核的Armbian安装进EMMC

### ISSUE THREAD

**Issue by xiayang0521** [7Ji/ampart#12]
有个板子是ssv6501的wifi，3.14内核的linux系统可以驱动，
看了该内核的Armbian安装boot的脚本，发现是直接修改/dev/boot分区如下：
```
mkdir -p $DIR_INSTALL/aboot
cd $DIR_INSTALL/aboot
dd if=/dev/boot of=boot.backup.img
abootimg -i /dev/boot > aboot.txt
abootimg -x /dev/boot
abootimg -u /dev/boot -k $IMAGE_KERNEL
abootimg -u /dev/boot -r $IMAGE_INITRD

echo "done."

if [ -f $IMAGE_DTB ] ; then
#    abootimg -u /dev/boot -s $IMAGE_DTB
    echo "Writing new dtb ..."
    dd if="$IMAGE_DTB" of="/dev/dtb" bs=262144 status=none && sync
    echo "done."
fi

echo "Write env bootargs"
/usr/sbin/fw_setenv initargs "root=/dev/data rootflags=data=writeback rw console=ttyS0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.repair=yes net.ifnames=0 mac=\${mac}"
```
但是我用上面的abootimg对boot分区进行处理 发现报错

我决定按ampart的方式进行分区，
```
ampart /dev/mmcblk0 -m dclone logo::8M:1 boot::256M:1 data::-1:4
```
之后，进行对他们格式化成ext4，写入对应boot文件和data中写入系统文件，修改uEnv.txt和fstab
修改启动命令
```
/usr/sbin/fw_setenv initargs "root=/dev/data rootflags=data=writeback rw console=ttyS0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.repair=yes net.ifnames=0 mac=\${mac}"
```
非常遗憾，没启动起来啊， 感觉是没读取到 /dev/data（按parted命令的分区，写系统也读取不到）

不知道我忽略了什么 或者此路是不是不通？

**Comment by 7Ji** [comment]
系统在外面的时候，能读取到Amlogic的分区表吗？3.14内核对于他们分区表的支持是比较迷的。Balbels的那个Armbian为了同时支持Rockchip和Allwinner的SoC，把mmc驱动里的分区相关给剃掉了。

**Comment by xiayang0521** [comment]
> 系统在外面的时候，能读取到Amlogic的分区表吗？3.14内核对于他们分区表的支持是比较迷的。Balbels的那个Armbian为了同时支持Rockchip和Allwinner的SoC，把mmc驱动里的分区相关给剃掉了。

外置优盘启动可以的，ls /dev/ 也能看到下面的data boot bootloader ...

如果修改外置优盘系统的boot分区的uEnv.txt，将root=/dev/data，
重新启动后会提示找不到/dev/data...我晕。。。。

**Comment by 7Ji** [comment]
root= 是在initramfs的阶段判断的，可能initramfs里没有打mmc的驱动？你看能重新打initramfs吗？Debian系用的应该是update-initramfs但是我不清楚怎么打包含所有驱动的

**Comment by xiayang0521** [comment]
行 我来试试

**Comment by xiayang0521** [comment]
> root= 是在initramfs的阶段判断的，可能initramfs里没有打mmc的驱动？你看能重新打initramfs吗？Debian系用的应该是update-initramfs但是我不清楚怎么打包含所有驱动的
> 
> 直接指定root=/dev/emmc的块设备试下，是报告文件系统不对还是找不到，找不到的话就说明initramfs里真的没mmc驱动根
据这里的
```
https://blog.51cto.com/u_13927568/5831684
```
第三个办法，initrd加入了aml_nftl_dev驱动，然后设置优盘BOOT分区uEnv的root=/dev/data，可以识别到了

```
root@amlogic:~# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    1   7.5G  0 disk
├─sda1         8:1    1   128M  0 part
└─sda2         8:2    1   7.2G  0 part
mmcblk0      179:0    0  14.7G  0 disk
mmcblk0boot0 179:32   0     4M  0 disk
mmcblk0boot1 179:64   0     4M  0 disk
mmcblk0rpmb  179:96   0     4M  0 disk
zram0        253:0    0 228.7M  0 disk [SWAP]
zram1        253:1    0 228.7M  0 disk [SWAP]
zram2        253:2    0 228.7M  0 disk [SWAP]
zram3        253:3    0 228.7M  0 disk [SWAP]
root@amlogic:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            753M     0  753M   0% /dev
tmpfs           183M  5.4M  178M   3% /run
/dev/data        14G  1.1G   13G   8% /
tmpfs           915M     0  915M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           915M     0  915M   0% /sys/fs/cgroup
tmpfs           915M     0  915M   0% /tmp
log2ram          50M   11M   40M  22% /var/log
tmpfs           183M     0  183M   0% /run/user/0
root@amlogic:~#
```
下面试下写入boot分区内容。

**Comment by xiayang0521** [comment]
> root= 是在initramfs的阶段判断的，可能initramfs里没有打mmc的驱动？你看能重新打initramfs吗？Debian系用的应该是update-initramfs但是我不清楚怎么打包含所有驱动的
> 
> 直接指定root=/dev/emmc的块设备试下，是报告文件系统不对还是找不到，找不到的话就说明initramfs里真的没mmc驱动

很不幸，没有优盘的boot分区引导，emmc里的系统起不来，即使我已经在/dev/boot分区里设置了启动文件...

**Comment by xiayang0521** [comment]
> > root= 是在initramfs的阶段判断的，可能initramfs里没有打mmc的驱动？你看能重新打initramfs吗？Debian系用的应该是update-initramfs但是我不清楚怎么打包含所有驱动的
> > 直接指定root=/dev/emmc的块设备试下，是报告文件系统不对还是找不到，找不到的话就说明initramfs里真的没mmc驱动
> 
> 很不幸，没有优盘的boot分区引导，emmc里的系统起不来，即使我已经在/dev/boot分区里设置了启动文件...

难道得混用一下？把boot分区占用的部分，采用parted 格式化成fat32，哈哈，我去，然后引导晶晨的/dev/data分区?

**Comment by 7Ji** [comment]
u-boot 应该能直接以fatload加载eMMC分区的文件吧，把启动脚本的分区编号改改就行了

**Comment by xiayang0521** [comment]
> u-boot 应该能直接以fatload加载eMMC分区的文件吧，把启动脚本的分区编号改改就行了

1. fatload是先加载initramfs，确定/分区,再加载zImage对吧？
我发现，一旦识别了晶晨分区，mbr分区就看不到了，或者说两钟分区只能见一种。

后果会不会是fatload是先加载initramfs，之后就看不到parted创建的boot分区，以至于虽然看到了/dev/data，但无法加载/boot/zImage？

如果initramfs和zImage同时加载，应该没这个问题，但我没成功启动，，，

2.在目前的分区布局下
``
ampart /dev/mmcblk0 -m dclone logo::8M:1 boot::256M:1 data::-1:4
``
如果我按bables150的的路，把zImage、initramfs和dtb注入安卓格式boot分区，
``
abootimg --create /dev/boot -f bootimg.cfg -k zImage -r initrd.img -s dtb.img
``
这样我试了下，似乎没起来，不知道哪里出了问题，是不是必须把安卓其他分区也加上。

3.不知道能不能把zImage中的晶晨分区驱动去掉，就能按现在的安装方式进行了。

**Comment by 7Ji** [comment]
为什么格式化要用parted? parted是分区工具，不是文件系统创建工具。创建分区，和创建文件系统，这两个操作是分开的。你用晶晨的分区表来储存 分区信息，然后直接在这里面划定的boot分区和root分区上分别创建FAT32和ext4文件系统不就行了？

**Comment by xiayang0521** [comment]
> 为什么格式化要用parted? parted是分区工具，不是文件系统创建工具。创建分区，和创建文件系统，这两个操作是分开的。你用晶晨的分区表来储存 分区信息，然后直接在这里面划定的boot分区和root分区上分别创建FAT32和ext4文件系统不就行了？

谢谢，尝试了很久，还是不照。最后突然想到，最初恩山应该会有人研究，挖了恩山的老教程，早该先搜一波。。。https://www.right.com.cn/forum/thread-327496-1-1.html。
