### ISSUE TITLE
ampart分区报错

### ISSUE THREAD

**Issue by LeosDing** [7Ji/ampart#17]
Mibox3 (MDZ-16-AA)
Amlogic S905
1G内存
4G EMMC 
通过刷mibox3-bare-but-mainline.img后正常从U盘引导Ambian
在Ambiance系统中运行命令输出如下：

> root@mibox3-armbian:~# ampart /dev/mmcblk1 --mode dclone
CLI interface: Mode is set to dclone
CLI interface: Operating on target file/block device '/dev/mmcblk1'
IO identify target type: '/dev/mmcblk1' is a block device, getting its size via ioctl
IO identify target type: size of '/dev/mmcblk1' is 3959422976
IO identify target type: Guessing content type by size
IO identify target type: Size larger than reserved partition, considering content full disk
IO identify target type: Getting content type via reading
IO identify target type: Content type unsupported due to magic unrecognisable
IO identify target type: Read result unsupported, using Size result
IO identify target type: target is a block device with a size of 3959422976 bytes, and contains the content of full diskCLI interface: Content type set as auto, will use the type identified earlier as type
CLI interface: Content auto identified as whole disk
CLI interface: Target is block device for a whole drive and we will try to re-read partitions after adjusting EPT
CLI describe options: mode dclone, operating on /dev/mmcblk1, content type disk, migration strategy: essential, dry run: no, reserved gap: 33554432 (32.000000M), generic gap: 8388608 (8.000000M), reserved offset: 37748736 (36.000000M), dtb offset: 4194304 (4.000000M)
IO seek DTB: Seeking to 41943040
DTB checksum: Calculated 00000000, Recorded 00000000
DTB read: Using first 256K in DTB partition
DTB read into buffer helper: Failed to identify DTB type
IO seek EPT: Seeking to 37748736
EPT report: 0 partitions in the table:
===================================================================================
ID| name            |          offset|(   human)|            size|(   human)| masks

> ===================================================================================
EPT report: Minumum block in table: 0x400000, 4194304, 4.000000M
CLI dispatcher: Dispatch to mode dclone
CLI mode dclone: Apply a snapshot taken in dsnapshot mode
CLI check PARG count: No PARG, early quit
root@mibox3-armbian:~#

**Comment by LeosDing** [comment]
如果执行

> \# ampart /dev/mmcblk1 --mode ecreate data:::

最后提示Failed to update DTB

> EPT report: 5 partitions in the table:
===================================================================================
ID| name            |          offset|(   human)|            size|(   human)| masks
> 0: bootloader                      0 (   0.00B)           400000 (   4.00M)      0
 1: env                        400000 (   4.00M)           800000 (   8.00M)      0
 2: cache                      c00000 (  12.00M)                0 (   0.00B)      0
    (GAP)                                                 1800000 (  24.00M)
 3: reserved                  2400000 (  36.00M)          4000000 (  64.00M)      0
 4: data                      6400000 ( 100.00M)         e5c00000 (   3.59G)      4
===================================================================================
EPT report: Minumum block in table: 0x400000, 4194304, 4.000000M
CLI mode ecreate: Old and new table same, no need to write
EPT pedantic offsets: layout now compatible with Amlogic's u-boot
EPT compare partitions: Names different
EPT is not pedantic: Part 2 does not met with the pedantic reserved
CLI write DTB from EPT: Result EPT is not pedantic, removing partitions node in DTB
CLI write DTB: Buffer and Dparts not both valid and contain partitions, refuse to continue
CLI write DTB from EPT: Failed to remove partitions node in DTB
CLI mode ecreate: Failed to update DTB`

**Comment by 7Ji** [comment]
> No PARG, early quit

is not an error. You've given no PARG to operate on so ampart only prints the current partitions.

> CLI mode ecreate: Old and new table same, no need to write

The table is not changed. It already was adjusted for max utilization in that burning image.

**Comment by LeosDing** [comment]
> > No PARG, early quit
> 
> is not an error. You've given no PARG to operate on so ampart only prints the current partitions.
这个PARG是传递的参数么？
> 
> > CLI mode ecreate: Old and new table same, no need to write
> 
> The table is not changed. It already was adjusted for max utilization in that burning image.
这条我执行了多次，所以Old and new table same

**Comment by LeosDing** [comment]
Reply： https://github.com/7Ji/ampart/issues/17#issuecomment-1899952816
这是对emmc.img做的操作吧，，我的是直接对/dev/mmcblk1做的操作，，你的意思是先对img做分区，然后直接dd回/dev/mmcblk1 ?
另外 aml_image_v2_packer 这个程序是哪儿提供的？
