### ISSUE TITLE
need help - boot start and stop.

### ISSUE THREAD

**Issue by okpapt** [7Ji/ampart#18]
Hello,

I have problem with x96mini s905w.
With rufus I put Armbian_24.5.0_amlogic_s905w_bullseye_5.15.153_server_2024.04.08.img.gz on my usb key.
Boot from it is OK, Armbian works well.
I tried reboot box alone, it start and stop.
I tried an **emmc backup armbian-ddbr** then **b** and it started quickly and it slowed down and nothing new.
3 hours later I rebooted after removing the usb key.
I have not backup of android os, I can't try restaure it.
I tried install armbian from usb key, it start and stop.
I think "maybe something is wrong in emmc".

If you want, I have some screenshot.

Does I need use ampart to partition or format it ? How can I do that ?
Do you have link of forum ?

I know nothing about android, linux, armbian, I do not speak english (google translate).
Thank you.

**Comment by 7Ji** [comment]
How is all this related to ampart but not https://github.com/ophub/amlogic-s9xxx-armbian ?

**Comment by okpapt** [comment]
Because ophub do not explain how use ampart !
