### ISSUE TITLE
Add arm32 version

### ISSUE THREAD

**Issue by firedevel** [7Ji/ampart#19]
my Amlogic Mi TV has a recovery run in arm32
i want to run this tool on my TV

I tried cross-compiling but I had a problem, it said -lz not found
cmd: make CC=arm-linux-gnueabi-gcc STRIP=arm-linux-gnueabi-strip ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-

<img width="755" alt="截屏2024-04-19 下午11 44 12" src="https://github.com/7Ji/ampart/assets/70802618/389538cc-14f3-4c43-9834-cdeddcb45162">

**Comment by 7Ji** [comment]
Set up cmake cross compiling toolchain and try to use that instead. The makefile is only for building natively.

Also I doubt ampart would work on 32-bit platform, they're a couple 64-bit data types I explicitly used.
