### ISSUE TITLE
[Official] Help wanted for encrypted DTB

### ISSUE THREAD

**Issue by 7Ji** [7Ji/ampart#4]
As documented in https://github.com/7Ji/ampart/issues/1 and https://github.com/7Ji/ampart/issues/2, the following devices are known to have encrypted DTBs which are generated with each vendor's unique private key:
 - Phicomm N1
 - Xiaomi devices with >=Android 8.0 firmware

I don't have either of the mentioned devices so it's impossible to reverse-engineer them

If there's anyone who either know the method to brute-force to crack the key or has the private key, please help to incorporate the support for these devices into ampart.

**Comment by edouardlicn123** [comment]
我有块没用的S905D你要不要？

**Comment by 7Ji** [comment]
谢谢，不需要，短时内我自己没有时间再亲自从零折腾一个盒子，今年在各种杂七杂八的事上浪费的时间太多了，年底还有考试。这个help wanted主要是希望有其他人能提出解密方法

**Comment by edouardlicn123** [comment]
建议咸鱼买个搞完再卖出去。

7Ji ***@***.***> 于 2022年12月26日周一 下午5:31写道：

**Comment by 7Ji** [comment]
I've documented an easy method to extract the encrypted DTB from a running Android system on my blog: https://7ji.github.io/crack/2023/01/08/decrypt-aml-dtb.html . And it's now possible to use ampart to re-partition eMMC on such devices. A small hint is also added to ampart to tell the users to extract DTB following the documentation if such DTB is found: https://github.com/7Ji/ampart/commit/086801d6a2043969d0c3157d393fda35ae6e9e14  
在我的博客上写了一个简单的从正在运行的安卓系统里提取DTB的方法：https://7ji.github.io/crack/2023/01/08/decrypt-aml-dtb.html 。现在用ampart在这种设备上给eMMC分区变得可行了。ampart里也加上让用户根据文档提取DTB的方法的提示，在发现可能加密的DTB的时候会提示：https://github.com/7Ji/ampart/commit/086801d6a2043969d0c3157d393fda35ae6e9e14  

Special thanks to Tomasz Jaskólski on helping with testing the method. I don't have such devices so I couldn't test it by myself.  
特别鸣谢Tomasz Jaskólski帮忙测试这个方法。我自己没有这种设备所以没法亲自测试

**Comment by yangfl** [comment]
补充一下，在已经刷掉原厂固件又不想刷回去的情况下提取 DTB：
1. 用 C 程序直接调用 SMC call 解密 DTB，示例：https://github.com/khadas/u-boot/blob/4c6694f6a8c250fcf88b4cdd1c76587f2b04d21a/common/partitions.c#L63
2. 观察 U-Boot 输出日志
   ```
   [store]To run cmd[emmc dtb_read 0x1000000 0x40000]
   ```
   记录地址，连接 USB 线进入 U-Boot USB 下载模式（短接 Maskrom 触点或 U-Boot 按回车进命令行后输入 `update` 回车）后，使用 amlogic `update` 工具执行 `update mread mem 0x1000000 normal 0x40000 uboot.dtb`
3. 如果没有 USB 线，也可以直接在 U-Boot 内执行 `md.b 1000000 40000`，然后从 UART 内记录下 DTB 内容
