### ISSUE TITLE
老大,盒子变砖了

### ISSUE THREAD

**Issue by pxshh** [7Ji/ampart#5]
盒子型号 hk1-rbox-x4  s905x4 64g ,ampart 是使用Emuelec自带的
查看下分区
Automatically chosen /dev/mmcblk0 as eMMC
29 partitions in the EPT
==================================================================================
id|name           |            start| (human)|            size| (human)|            end| (human)|masks
==================================================================================
 0 bootloader                      0    0.00B           400000    4.00M           400000    4.00M  0
   (gap)                                               2000000   32.00M
 1 reserved                  2400000   36.00M          4000000   64.00M          6400000  100.00M  0
   (gap)                                                800000    8.00M
 2 cache                     6c00000  108.00M                0    0.00B          6c00000  108.00M  0
   (gap)                                                800000    8.00M
 3 env                       7400000  116.00M           800000    8.00M          7c00000  124.00M  0
   (gap)                                                800000    8.00M
 4 frp                       8400000  132.00M           200000    2.00M          8600000  134.00M  1
   (gap)                                                800000    8.00M
 5 factory                   8e00000  142.00M           800000    8.00M          9600000  150.00M 17
   (gap)                                                800000    8.00M
 6 vendor_boot_a             9e00000  158.00M          1800000   24.00M          b600000  182.00M  1
   (gap)                                                800000    8.00M
 7 vendor_boot_b             be00000  190.00M          1800000   24.00M          d600000  214.00M  1
   (gap)                                                800000    8.00M
 8 tee                       de00000  222.00M          2000000   32.00M          fe00000  254.00M  1
   (gap)                                                800000    8.00M
 9 logo                     10600000  262.00M           800000    8.00M         10e00000  270.00M  1
   (gap)                                                800000    8.00M
10 misc                     11600000  278.00M           200000    2.00M         11800000  280.00M  1
   (gap)                                                800000    8.00M
11 dtbo_a                   12000000  288.00M           200000    2.00M         12200000  290.00M  1
   (gap)                                                800000    8.00M
12 dtbo_b                   12a00000  298.00M           200000    2.00M         12c00000  300.00M  1
   (gap)                                                800000    8.00M
13 cri_data                 13400000  308.00M           800000    8.00M         13c00000  316.00M  2
   (gap)                                                800000    8.00M
14 param                    14400000  324.00M          1000000   16.00M         15400000  340.00M  2
   (gap)                                                800000    8.00M
15 odm_ext_a                15c00000  348.00M          1000000   16.00M         16c00000  364.00M  1
   (gap)                                                800000    8.00M
16 odm_ext_b                17400000  372.00M          1000000   16.00M         18400000  388.00M  1
   (gap)                                                800000    8.00M
17 oem_a                    18c00000  396.00M          2000000   32.00M         1ac00000  428.00M  1
   (gap)                                                800000    8.00M
18 oem_b                    1b400000  436.00M          2000000   32.00M         1d400000  468.00M  1
   (gap)                                                800000    8.00M
19 boot_a                   1dc00000  476.00M          4000000   64.00M         21c00000  540.00M  1
   (gap)                                                800000    8.00M
20 boot_b                   22400000  548.00M          4000000   64.00M         26400000  612.00M  1
   (gap)                                                800000    8.00M
21 rsv                      26c00000  620.00M          1000000   16.00M         27c00000  636.00M  1
   (gap)                                                800000    8.00M
22 metadata                 28400000  644.00M          1000000   16.00M         29400000  660.00M  1
   (gap)                                                800000    8.00M
23 vbmeta_a                 29c00000  668.00M           200000    2.00M         29e00000  670.00M  1
   (gap)                                                800000    8.00M
24 vbmeta_b                 2a600000  678.00M           200000    2.00M         2a800000  680.00M  1
   (gap)                                                800000    8.00M
25 vbmeta_system_a          2b000000  688.00M           200000    2.00M         2b200000  690.00M  1
   (gap)                                                800000    8.00M
26 vbmeta_system_b          2ba00000  698.00M           200000    2.00M         2bc00000  700.00M  1
   (gap)                                                800000    8.00M
27 super                    2c400000  708.00M         90000000    2.25G         bc400000    2.94G  1
   (gap)                                                800000    8.00M
28 userdata                 bcc00000    2.95G        dd2c00000   55.29G        e8f800000   58.24G  4
与你的教程中的例子差不多,没多想.就直接输入一条命令
` ampart /dev/mmcblk0  --mode dclone data::-1:4`
执行后 最后提示 CLI write EPT: Write successful
又看了下分区情况
Automatically chosen /dev/mmcblk0 as eMMC
5 partitions in the EPT
==================================================================================
id|name           |            start| (human)|            size| (human)|            end| (human)|masks
==================================================================================
 0 bootloader                      0    0.00B           400000    4.00M           400000    4.00M  0
   (gap)                                               2000000   32.00M
 1 reserved                  2400000   36.00M          4000000   64.00M          6400000  100.00M  0
   (gap)                                                800000    8.00M
 2 cache                     6c00000  108.00M                0    0.00B          6c00000  108.00M  0
   (gap)                                                800000    8.00M
 3 env                       7400000  116.00M           800000    8.00M          7c00000  124.00M  0
   (gap)                                                800000    8.00M
 4 data                      8400000  132.00M        e87400000   58.11G        e8f800000   58.24G  4
==================================================================================
于是启动下,发现变砖了.老大,哪里搞错了啊

**Comment by 7Ji** [comment]
X4不能用 `data::-1:4`这个快照，除了data还有两个分区不能删除，文档里有写

https://github.com/7Ji/ampart/blob/ampart/doc/available-modes.md#note--%E7%AC%94%E8%AE%B0

pxshh ***@***.***> 于 2022年12月29日周四 下午11:36写道：

**Comment by pxshh** [comment]
好的,谢谢,可以了.另外想问下masks(掩码)有啥用啊,文档中好像没说明.

**Comment by 7Ji** [comment]
这个掩码对于要把安卓整掉的用途来说无意义，只对安卓相关的刷机有用

掩码应该为不重复的任意2的整倍数的数的和，也就是说在一个字节上各个比特为置为1各自有对应意思

1 标记这个分区对于启动流程有用
2 标记安卓的系统分区
4 标记安卓的数据分区，刷机时数据可以保留

没有置任何位的就是全0，是无论如何都会有的分区的默认掩码（bootloader, reserved这样的）

更高位Amlogic理论上没有划分，但是我的x4盒子有个掩码17的分区（16+1）

大多数情况下你自己划定的分区用4就行

pxshh ***@***.***> 于 2022年12月30日周五 上午11:23写道：
