### ISSUE TITLE
EE的分区表能否改为GPT

### ISSUE THREAD

**Issue by edouardlicn123** [7Ji/ampart#8]
因为某些奇怪的理由，我需要在EE上建立4个以上的主分区，但通过Gparted观察似乎它的分区表是MSDOS（我理解为MBR那套）。似乎这种分区表下是无法建立四个以上主分区的。因此我有个想法，但又不想花时间折腾，想先问问你的看法。就是是否我可以先把各个分区的数据单独导出，然后重建分区表为GPT，再将数据dd回去？重点在于EE是否支持GPT表，或者机顶盒是否支持？

**Comment by 7Ji** [comment]
问题的关键不在于EE，而是机顶盒。EE的内核是支持GPT分区表的，你可以在一个无修改的EE运行时插上一个GPT的硬盘/U盘观察。u-boot编译时必须设置`CONFIG_EFI_PARTITION=y`才能识别GPT分区表，主线u-boot里这个默认开启，aml的默认关闭，且你根本不知道各个厂家编译他们系统用的u-boot的时候开没开这个选项。

> 再将数据dd回去

如果你不想破坏完整性，应该是整个分区dd再dd；如果你只是要数据，只要rsync或者bsdtar

**Comment by 7Ji** [comment]
我有几个问题，
1. >在**EE上**建立4个以上的主分区  
   - 你是要把移动硬盘当成装EE+Rom的盘吗？我不太建议把EE本身放移动硬盘，这样的话性能有影响而且浪费硬盘空间，而且不便于反复重装系统，重写镜像什么的。最好是用4.6加入的eemount的多驱动器挂载功能把移动硬盘本身就有的一个区用来放Rom：https://github.com/EmuELEC/EmuELEC/wiki/Mixing-ROMs-from-multiple-drives 。eemount就是我去年说过的挂载项目：https://github.com/7Ji/eemount ，装系统的盘和你Rom盘上的Rom可以共存。
2. >在EE上建立**4个以上**的主分区  
   - 我还是觉得有些匪夷所思……我从几年前开始所有硬盘都是能只有一个分区就只有一个分区了，哪怕十几T的硬盘都是GPT+单分区，或者直接在整个硬盘上建文件系统完全不要分区表(`mkfs.ext4 /dev/sda`这样)，或者整个硬盘做LVM的PV，若干个硬盘的VG里再只建一个分区。为什么需要这么多的分区？如果你是想搞多启动的话，各种系统也不是必要有自己的root的，你可能习惯了挂载源一定是文件系统的根目录，但是子文件夹也可以是挂载源的，如此一来要整洁很多。
3. >在EE上建立4个以上的**主分区**
   - 一定要是主分区吗？MBR分区表是可以建立扩展分区的，扩展分区里就可以再建立若干分区。早年机械硬盘+xp的ghost装机时代就流行分5个以上区（因为早期ghost镜像作者的习惯），第4、5就是放在扩展分区里的。

**Comment by 7Ji** [comment]
这个问题和ampart关系不大，先在这边关掉。要讨论EE问题的话，在我的EE仓库里开 https://github.com/7Ji/EmuELEC
